export const sampleEmails=[
  {
    "id": 1,
    "name": "Alex Morgan",
    "initials": "AM",
    "email": "alex@example.com",
    "subject": "About the project deadline",
    "time": "10:42 AM",
    "is_unread": true,
    "is_starred": true,
    "is_harsh": true,
    "color": "#e9e6fa",
    "original": "Hi Jamie,\n\nThis is the third time I’ve asked for the updated timeline. It’s ridiculous that I still don’t have it. We can’t keep wasting time because you can’t get your act together.\n\nI need the revised plan by 3 PM today. No more excuses.\n\nAlex",
    "kind": "Hi Jamie,\n\nI’m following up on the updated timeline, which I’ve now requested three times. The delay is holding up our work, and I’m concerned about keeping the project on track.\n\nPlease send the revised plan by 3 PM today.\n\nAlex",
    "draft": "I’m working on it. Maybe if you stopped changing the requirements every five minutes, we’d actually be on schedule.",
    "reply": "Hi Alex,\n\nI’m working on the revised plan. The frequent changes to the requirements have affected the timeline. Could we agree on a stable set of requirements so we can keep the project on track?\n\nJamie",
    "facts": "Third request · Revised plan due today at 3 PM",
    "kind_subject": "Updated timeline needed today"
  },
  {
    "id": 2,
    "name": "Priya Shah",
    "initials": "PS",
    "email": "priya@example.com",
    "subject": "A few thoughts on your proposal",
    "time": "9:18 AM",
    "is_unread": true,
    "is_starred": false,
    "is_harsh": true,
    "color": "#f9e9df",
    "original": "Jamie,\n\nDid you even read the brief? This proposal completely misses the point. The budget section is a mess and the scope makes no sense.\n\nFix the budget and clarify what’s included before our Thursday meeting.\n\nPriya",
    "kind": "Hi Jamie,\n\nThe proposal doesn’t yet address the brief. The budget needs revision, and the scope needs to be clearer.\n\nPlease revise the budget and clarify what’s included before our Thursday meeting.\n\nPriya",
    "draft": "Your brief was vague. You can’t expect me to read your mind.",
    "reply": "Hi Priya,\n\nI found parts of the brief unclear. Could you clarify your expectations for the budget and scope so I can address them accurately?\n\nJamie",
    "facts": "Revise budget and scope · Before Thursday’s meeting",
    "kind_subject": "Budget and scope revisions"
  },
  {
    "id": 3,
    "name": "Sophie Chen",
    "initials": "SC",
    "email": "sophie@example.com",
    "subject": "Coffee next week? ☕",
    "time": "Yesterday",
    "is_unread": false,
    "is_starred": true,
    "is_harsh": false,
    "color": "#e0eee9",
    "original": "Hi Jamie,\n\nIt’s been a while! Would you be up for coffee next week? I’d love to hear how the new project is going.\n\nTuesday or Wednesday afternoon works for me. Let me know what suits you.\n\nSophie",
    "kind": "Hi Jamie,\n\nIt has been a while. Would you like to meet for coffee next week? I would love to hear about the new project.\n\nTuesday or Wednesday afternoon works for me. Please let me know what suits you.\n\nSophie",
    "draft": "",
    "reply": null,
    "facts": null,
    "kind_subject": "Coffee next week"
  },
  {
    "id": 4,
    "name": "Daniel Brooks",
    "initials": "DB",
    "email": "daniel@example.com",
    "subject": "Re: The handover documents",
    "time": "Yesterday",
    "is_unread": false,
    "is_starred": false,
    "is_harsh": true,
    "color": "#e5edf9",
    "original": "Jamie,\n\nThese handover notes are useless. Half the links are broken and nobody knows who owns what. I shouldn’t have to chase you for basic information.\n\nSend working links and an owner for each task by Friday.\n\nDaniel",
    "kind": "Hi Jamie,\n\nThe handover notes are missing some information we need: half the links aren’t working, and task ownership is unclear.\n\nPlease send working links and identify an owner for each task by Friday.\n\nDaniel",
    "draft": "Check properly before blaming me. Some of those links need access permissions.",
    "reply": "Hi Daniel,\n\nSome of the links require access permissions. Could you check whether you have access before concluding that they’re broken?\n\nJamie",
    "facts": "Working links and task owners · Due Friday",
    "kind_subject": "Handover links and task owners"
  },
  {
    "id": 5,
    "name": "Maya Patel",
    "initials": "MP",
    "email": "maya@example.com",
    "subject": "You made our day",
    "time": "Wed",
    "is_unread": false,
    "is_starred": false,
    "is_harsh": false,
    "color": "#f6e6ec",
    "original": "Hi Jamie,\n\nJust wanted to say thank you for helping with the launch yesterday. Your calm approach made such a difference to the team.\n\nWe’re lucky to have you.\n\nMaya",
    "kind": "Hi Jamie,\n\nThank you for helping with the launch yesterday. Your calm approach made a difference to the team.\n\nWe are lucky to have you.\n\nMaya",
    "draft": "",
    "reply": null,
    "facts": null,
    "kind_subject": "Thank you for helping with the launch"
  },
  {
    "id": 6,
    "name": "Design team",
    "initials": "DT",
    "email": "design@example.com",
    "subject": "Friday inspiration & a small win",
    "time": "Wed",
    "is_unread": false,
    "is_starred": false,
    "is_harsh": false,
    "color": "#eee9db",
    "original": "Hello team,\n\nThe new onboarding screens are ready for a first look. Thank you to everyone who shared feedback this week.\n\nBring one idea you liked to our Friday catch-up. See you there!\n\nThe design team",
    "kind": "Hello team,\n\nThe new onboarding screens are ready for a first look. Thank you to everyone who shared feedback this week.\n\nPlease bring one idea you liked to our Friday catch-up. See you there!\n\nThe design team",
    "draft": "",
    "reply": null,
    "facts": null,
    "kind_subject": "Onboarding screens and Friday catch-up"
  }
];
